#pragma once
#include <algorithm>
#include <vector>
#include <map>
#include <unordered_map>
#include <set>
#include <unordered_set>
#include <string>
#include <memory>
#include <queue>
#include <stack>
#include <cassert>
#include <functional>
